### ISSUE TITLE
Feature Request: I want the bot to link to the big ol' doinks video on command

### ISSUE THREAD

**Issue by i-am-knots** [Gavisann/CloudBot#6]
I'd like to be able to issue an IRC command and have the bot return a string, and either a video link or embedded video if possible on irccloud. 

Proposed usage:
    `.doink < any arbitrary string | user >` 
will return:
   `Big ol' doinks in Amish....... Gang. https://www.youtube.com/watch?v=FKfX-BXGr9M`
Or return:
   An embedded video of the above link, with the caption "Big ol' doinks in Amish........ Gang."

**Comment by Gavisann** [comment]
added https://github.com/Gavisann/CloudBot/commit/762a0e6dbcd6f7270e6cc9b045d4b568e44ffd0b
